<?xml version="1.0" encoding="UTF-8" ?>

<?xml-stylesheet type="text/xsl" href="customer.xsl"?>



<!DOCTYPE customer [

<!ELEMENT customer (customer_data)>

<!ELEMENT customer_data (customer_code, customer_firstname, customer_lastname, customer_age, customer_phone)>

<!ELEMENT customer_code (#PCDATA)>

<!ELEMENT customer_firstname (#PCDATA)>

<!ELEMENT customer_lastname (#PCDATA)>

<!ELEMENT customer_age (#PCDATA)>

<!ELEMENT customer_phone (#PCDATA)>



]>



<customer>

    <customer_data>

        <customer_code>001</customer_code>

        <customer_firstname>ห้าย่า</customer_firstname>

        <customer_lastname>บูญมี</customer_lastname>

        <customer_age>30</customer_age>

        <customer_phone>087-861-190</customer_phone>

    </customer_data>

    <customer_data>

        <customer_code>002</customer_code>

        <customer_firstname>สอหมาย</customer_firstname>

        <customer_lastname>กะบังลิน</customer_lastname>

        <customer_age>24</customer_age>

        <customer_phone>033-012-966</customer_phone>

    </customer_data>

    <customer_data>

        <customer_code>003</customer_code>

        <customer_firstname>แล้วไง</customer_firstname>

        <customer_lastname>ใครแคร์</customer_lastname>

        <customer_age>18</customer_age>

        <customer_phone>031-564-916</customer_phone>

    </customer_data>

    <customer_data>

        <customer_code>004</customer_code>

        <customer_firstname>หมีควาย</customer_firstname>

        <customer_lastname>หมายจันทร์</customer_lastname>

        <customer_age>19</customer_age>

        <customer_phone>098-315-619</customer_phone>

    </customer_data>

    <customer_data>

        <customer_code>005</customer_code>

        <customer_firstname>ปลาทง</customer_firstname>

        <customer_lastname>บรงมงมง</customer_lastname>

        <customer_age>22</customer_age>

        <customer_phone>084-619-614</customer_phone>

    </customer_data>

</customer>
